name: container

on:
  workflow_dispatch:

env:
  ARCH: powerpc

jobs:
  kernel:
    runs-on: ubuntu-latest

    container:
      image: linuxppc/build:ubuntu-20.04-x86_64
      options: --user 1001
      volumes:
        - /home/runner/work/_temp:/output

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'linux'

    - name: build
      run: |
        cd linux
        export ARCH=powerpc
        export DEFCONFIG=ppc64le_defconfig
        export JFACTOR=$(nproc)
        export KBUILD_BUILD_TIMESTAMP=$(date +%Y-%m-%d)
        export CROSS_COMPILE=powerpc64le-linux-gnu-
        export QUIET=1 
        /bin/container-build.sh kernel
