# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARCH: powerpc
      TARGET: kernel
      SUBARCH: ppc64le
      IMAGE: ubuntu-20.04
      DEFCONFIG: ppc64le_defconfig

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'linux'

    - name: build
      run: ./linux/arch/powerpc/tools/ci-build.sh
