name: powerpc/test

# Controls when the action will run.
on:
  # This allows the build to be triggered manually via the github UI.
  workflow_dispatch:

  # This triggers the build on a push to any branch named ci/powerpc/<something>
  push:
    branches:
    - 'ci/powerpc/**'

jobs:
  kernel:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        defconfig: [ppc64, ppc40x]
        image: [ubuntu-20.04]
        subarch: [ppc64]

    env:
      ARCH: powerpc
      TARGET: kernel
      SUBARCH: ${{ matrix.subarch }}
      IMAGE: ${{ matrix.image }}
      DEFCONFIG: ${{ matrix.defconfig }}
      MODULES: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'linux'

    - name: Build
      run: ./linux/arch/powerpc/tools/ci-build.sh

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.defconfig }}-${{ matrix.image }}
        path: |
          output/vmlinux
          output/.config
          output/System.map
          output/modules.tar.bz2
          output/arch/powerpc/boot/zImage
          output/arch/powerpc/boot/uImage
