name: powerpc/test

# Controls when the action will run.
on:
  # This allows the build to be triggered manually via the github UI.
  workflow_dispatch:

  # This triggers the build on a push to any branch named ci/powerpc/<something>
  push:
    branches:
    - 'ci/powerpc/**'

jobs:
  kernel:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        defconfig: [ppc64, ppc40x]
        image: [ubuntu-20.04]
        subarch: [ppc64]

    env:
      ARCH: powerpc
      TARGET: kernel
      SUBARCH: ${{ matrix.subarch }}
      IMAGE: ${{ matrix.image }}
      DEFCONFIG: ${{ matrix.defconfig }}
      MODULES: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'linux'

    - name: Build
      run: ./linux/arch/powerpc/tools/ci-build.sh

    - name: Archive vmlinux
      uses: actions/upload-artifact@v2
      with:
        name: vmlinux
        path: output/vmlinux

    - name: Archive config
      uses: actions/upload-artifact@v2
      with:
        name: config
        path: output/.config

    - name: Archive System.map
      uses: actions/upload-artifact@v2
      with:
        name: System.map
        path: output/System.map

    - name: Archive modules
      uses: actions/upload-artifact@v2
      with:
        name: modules.tar.bz2
        path: output/modules.tar.bz2
        if-no-files-found: ignore
        # Not all builds produce modules

    - name: Archive zImage
      uses: actions/upload-artifact@v2
      with:
        name: zImage
        path: output/arch/powerpc/boot/zImage
        if-no-files-found: ignore
        # Not all builds produce zImage

    - name: Archive uImage
      uses: actions/upload-artifact@v2
      with:
        name: uImage
        path: output/arch/powerpc/boot/uImage
        if-no-files-found: ignore
        # Not all builds produce uImage
